name: Deploy Website to Hostinger via FTP

on:
  push:
    branches:
      - main  # or master if that's your main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install FTP Deploy
        run: |
          sudo apt-get update
          sudo apt-get install -y lftp

      - name: Deploy to FTP Server
        run: |
          lftp -f "
          open ftp://$FTP_USERNAME:$FTP_PASSWORD@$FTP_HOST
          mirror -R ./ $FTP_TARGET_DIR --ignore-time --delete
          "
        env:
          FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
          FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
          FTP_HOST: ${{ secrets.FTP_HOST }}
          FTP_TARGET_DIR: "public_html"  # You can modify this to match your directory



