name: Deploy to importanceleadership.com
on:
  push:
    branches: [ main ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server: ftp.importanceleadership.com
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./  # Your built files
        server-dir: /public_html/
        exclude: |
          .git*
          .github/*
          README.md
